language: python
python:
  - "2.7"
services:
  - docker
before_install:
  - sudo apt-get -qq update
  - docker build -t tendrl-ansible-rpmlint -f .travis.rpmlint.dockerfile
install:
  - pip install yamllint
  - pip install ansible-lint==3.4.21
script:
  - yamllint .
  - ansible-lint prechecks.yml
  - ansible-lint -x ANSIBLE0016,ANSIBLE0010 site.yml
  - docker run tendrl-ansible-rpmlint
