---
- hosts: tendrl-servers
  roles:
    - tendrl-server
    - geerlingguy.apache
    - ceph-installer

- hosts: all
  tasks:
  roles:
    - utils
    - tendrl-node
    - geerlingguy.ntp
    - role: access
      name: mrugesh
    - role: access
      name: nishant

- hosts: tendrl-servers
  roles:
    - perf-mon

- hosts: ceph-servers
  roles:
    - ceph-node

