---
# This Ansible playbook to install Tendrl, automating steps from upstream
# *Tendrl Package Installation Reference* wiki page.

- hosts: tendrl_server
  user: root
  roles:
    - tendrl-ansible.grafana-repo
    - tendrl-ansible.tendrl-copr
    - tendrl-ansible.tendrl-server

- hosts: gluster_servers
  user: root
  roles:
    - tendrl-ansible.tendrl-copr
    - tendrl-ansible.tendrl-storage-node
