---
# tasks file for tendrl-server

- name: Use ip address of default ipv4 network interface for etcd
  set_fact:
    etcd_ip_address: '{{ ansible_default_ipv4.address }}'
  when: etcd_ip_address is undefined

- name: Use ip address of default ipv4 network interface for graphite
  set_fact:
    graphite_ip_address: '{{ ansible_default_ipv4.address }}'
  when: graphite_ip_address is undefined

- name: Use ip address of default ipv4 network interface for apache
  set_fact:
    httpd_ip_address: '{{ ansible_default_ipv4.address }}'
  when: httpd_ip_address is undefined

- name: Use ansible detected fqdn as apache ServerName
  set_fact:
    httpd_server_name: '{{ ansible_fqdn }}'
  when: httpd_server_name is undefined

- debug:
    msg:
      - "Using {{ etcd_ip_address }} as etcd ip address."
      - "Using {{ graphite_ip_address }} as graphite ip address."
      - "Using {{ httpd_ip_address }} as apache ip address."
      - "Using {{ httpd_server_name }} as apache ServerName."

- include: etcd.yml
- include: tendrl-node-agent.yml
- include: tendrl-api.yml
- include: tendrl-ui.yml
- include: tendrl-monitoring-integration.yml
- include: tendrl-notifier.yml
- include: httpd-ssl.yml
  when: tendrl_ssl_enabled == True

- name: Enable httpd service
  service:
    name=httpd
    enabled=yes

- name: Start httpd service
  service:
    name=httpd
    state=started
