- name: Install yum priorities
  package:
    name: yum-plugin-priorities
    state: installed

- name: Setup Ceph repos
  yum_repository:
    name: ceph-jewel
    description: Ceph packages for $basearch
    baseurl: https://download.ceph.com/rpm-jewel/el7/$basearch
    enabled: 1
    priority: 2
    gpgcheck: 0
    gpgkey: https://download.ceph.com/keys/release.asc

- name: Setup Ceph repos
  yum_repository:
    name: ceph-jewel-noarch
    description: Ceph noarch packages
    baseurl: https://download.ceph.com/rpm-jewel/el7/noarch
    enabled: 1
    priority: 2
    gpgcheck: 0
    gpgkey: https://download.ceph.com/keys/release.asc
