---

- name: Gather information on etcd_cert_file
  stat:
    path: "{{ etcd_cert_file }}"
  register: etcd_crt

- name: Gather information on etcd_key_file
  stat:
    path: "{{ etcd_key_file }}"
  register: etcd_key

- name: Gather information on etcd_trusted_ca_file
  stat:
    path: "{{ etcd_trusted_ca_file }}"
  register: etcd_trusted_ca

- name: Check that file specified in etcd_cert_file actually exists
  assert:
    that:
      - etcd_crt.stat.exists == True
    msg: >
      File specified in etcd_cert_file doesn't exist on remote machine.
      Please specify path to etcd certificate file in the variable and rerun
      the playbook.

- name: Check that file specified in etcd_key_file actually exists
  assert:
    that:
      - etcd_key.stat.exists == True
    msg: >
      File specified in etcd_key_file doesn't exist on remote machine.
      Please specify path to etcd key file in the variable and rerun the
      playbook.

- name: Check that file specified in etcd_trusted_ca_file actually exists
  assert:
    that:
      - etcd_trusted_ca.stat.exists == True
    msg: >
      File specified in etcd_trusted_ca_file doesn't exist on remote machine.
      Please specify path to trusted certificate authority in the variable and
      rerun the playbook.
