---

- name: ensure rsyslog is enabled
  service:
    name=rsyslog
    enabled=yes
  tags:
    - service-enabled

- name: ensure rsyslog is running
  service:
    name=rsyslog
    state=started
  tags:
    - service-started
