---
# tasks file for grafana-repo

- name: Install Grafana stable repo
  copy:
    src='grafana.repo'
    dest=/etc/yum.repos.d

- name: Install Grafana stable rpm-gpg key
  copy:
    src='RPM-GPG-KEY-grafana'
    dest=/etc/pki/rpm-gpg

- name: Import Grafana stable rpm-gpg key
  rpm_key:
    key=/etc/pki/rpm-gpg/RPM-GPG-KEY-grafana
    state=present
  register: rpm_key_grafana

# WORKAROUND for issues with grafana repo
# https://github.com/ansible/ansible/issues/20711
- name: "WORKAROUND for issues with grafana repo: make yum cache"
  command: "yum makecache -y --disablerepo='*' --enablerepo='grafana'"
  when: rpm_key_grafana.changed
  register: task_result
  until: task_result|success
  retries: 5
  delay: 5
  tags:
   - skip_ansible_lint
